# -*- coding: utf-8 -*-
"""E-Field_aedtplt_reconfiguration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dGV2Sxi2dAEc3QC6NKxjQa3TbPe5P1n

8 reconfigurations of E-Field (aedtplt)
"""

# ============================================
# Colab script for scalar E-field .aedtplt files
# Output:
#   1) Excel summary with E_peak, E_mean, E_standardDeviation in ROI
#   2) Optional contour plots for visual checking
# ============================================

import re
import io
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.tri as mtri
from google.colab import files

# =========================================================
# 1) Upload all .aedtplt files
# =========================================================
uploaded = files.upload()

# =========================================================
# 2) Parsing helpers
# =========================================================
def extract_block(text, key):
    """
    Extract content inside key(...)
    Works for large blocks like Nodes(...), Elements(...), ElemSolution(...)
    """
    start = text.find(f"{key}(")
    if start == -1:
        raise ValueError(f"{key}( not found in file")

    i = start + len(key) + 1
    depth = 1
    out = []

    while i < len(text) and depth > 0:
        ch = text[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                break
        out.append(ch)
        i += 1

    return "".join(out)

def parse_float_list(s):
    return [float(x) for x in re.findall(r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', s)]

def parse_int_list(s):
    return [int(x) for x in re.findall(r'[-+]?\d+', s)]

def parse_nodes(nodes_text):
    vals = parse_float_list(nodes_text)
    pts = np.array(vals).reshape(-1, 3)
    return pts  # (N, 3)

def parse_elements(elements_text):
    """
    Based on your uploaded file:
    Elements(total_nodes, total_elements, repeat[5 header ints + n_nodes node indices])

    In your sample:
      all elements are 6-node triangles
      each element record looks like:
      [2, 3, 3, 0, 6, n1, n2, n3, n4, n5, n6]
    """
    arr = parse_int_list(elements_text)

    total_nodes = arr[0]
    total_elements = arr[1]

    pos = 2
    elements = []

    for _ in range(total_elements):
        header = arr[pos:pos+5]
        n_nodes = header[4]
        conn = arr[pos+5:pos+5+n_nodes]
        pos += 5 + n_nodes

        elements.append({
            "header": header,
            "n_nodes": n_nodes,
            "conn": conn
        })

    return total_nodes, total_elements, elements

def parse_elem_solution(elemsol_text):
    """
    ElemSolution(minval, maxval, n_per_element, ... field values ...)

    For your uploaded scalar E-field file:
      n_per_element = 6
    """
    vals = parse_float_list(elemsol_text)
    minval = vals[0]
    maxval = vals[1]
    n_per_element = int(vals[2])
    data = vals[3:]
    return minval, maxval, n_per_element, data

def build_nodal_scalar_field(nodes, elements, n_per_element, elem_data):
    """
    Build nodal scalar field by averaging repeated nodal contributions.
    This is correct for scalar field exports like Mag_E.
    """
    nodal_sum = np.zeros(len(nodes), dtype=float)
    nodal_count = np.zeros(len(nodes), dtype=int)

    pos = 0
    for el in elements:
        n_nodes = el["n_nodes"]
        vals = elem_data[pos:pos+n_per_element]
        pos += n_per_element

        if n_per_element != n_nodes:
            raise ValueError(
                f"This parser expects scalar field export. "
                f"Found n_per_element={n_per_element}, n_nodes={n_nodes}."
            )

        for node_idx_1based, fval in zip(el["conn"], vals):
            idx = node_idx_1based - 1
            nodal_sum[idx] += fval
            nodal_count[idx] += 1

    nodal_field = nodal_sum / np.where(nodal_count == 0, 1, nodal_count)
    return nodal_field

def detect_plane(coords):
    """
    Detect which axis is constant, then identify plane.
    """
    xr = np.max(coords[:, 0]) - np.min(coords[:, 0])
    yr = np.max(coords[:, 1]) - np.min(coords[:, 1])
    zr = np.max(coords[:, 2]) - np.min(coords[:, 2])

    ranges = {"x": xr, "y": yr, "z": zr}
    fixed_axis = min(ranges, key=ranges.get)

    if fixed_axis == "x":
        plane = "YZ"
        u = coords[:, 1]
        v = coords[:, 2]
        u_name, v_name = "y", "z"
    elif fixed_axis == "y":
        plane = "XZ"
        u = coords[:, 0]
        v = coords[:, 2]
        u_name, v_name = "x", "z"
    else:
        plane = "XY"
        u = coords[:, 0]
        v = coords[:, 1]
        u_name, v_name = "x", "y"

    return plane, fixed_axis, u, v, u_name, v_name

def parse_mode_and_plane_from_filename(fname):
    """
    Expected examples:
      [000] E-XZ.aedtplt
      [111] E-YZ.aedtplt
    """
    mode_match = re.search(r'\[?([01]{3})\]?', fname)
    plane_match = re.search(r'(XZ|YZ|XY)', fname, re.IGNORECASE)

    mode = mode_match.group(1) if mode_match else "UNK"
    plane_from_name = plane_match.group(1).upper() if plane_match else "UNK"

    return mode, plane_from_name

def parse_aedtplt_scalar_file(file_bytes, fname=""):
    text = io.BytesIO(file_bytes).read().decode("utf-8", errors="ignore")

    nodes = parse_nodes(extract_block(text, "Nodes"))
    _, _, elements = parse_elements(extract_block(text, "Elements"))
    minval, maxval, n_per_element, elem_data = parse_elem_solution(extract_block(text, "ElemSolution"))

    field = build_nodal_scalar_field(nodes, elements, n_per_element, elem_data)
    plane_detected, fixed_axis, u, v, u_name, v_name = detect_plane(nodes)

    mode, plane_from_name = parse_mode_and_plane_from_filename(fname)

    df = pd.DataFrame({
        "x": nodes[:, 0],
        "y": nodes[:, 1],
        "z": nodes[:, 2],
        "Field": field
    })

    return {
        "filename": fname,
        "mode": mode,
        "plane_name": plane_from_name,
        "plane_detected": plane_detected,
        "fixed_axis": fixed_axis,
        "u": u,
        "v": v,
        "u_name": u_name,
        "v_name": v_name,
        "df": df,
        "minval_file": minval,
        "maxval_file": maxval
    }

# =========================================================
# 3) Parse all uploaded files
# =========================================================
parsed = {}

for fname, content in uploaded.items():
    try:
        item = parse_aedtplt_scalar_file(content, fname=fname)
        parsed[fname] = item
        print(f"Parsed: {fname} | mode={item['mode']} | plane={item['plane_detected']}")
    except Exception as e:
        print(f"Failed: {fname} -> {e}")

# =========================================================
# 4) Define ROI for each plane
#    Edit these values to match your Rx region
# =========================================================

# Example ROI for XZ plane
ROI_XZ = {
    "x_min": -1,
    "x_max": 2,
    "z_min": -20,
    "z_max": -10
}

# Example ROI for YZ plane
ROI_YZ = {
    "y_min": -10,
    "y_max": 10,
    "z_min": -3,
    "z_max": 2
}

# =========================================================
# 5) Compute ROI metrics
# =========================================================
summary_rows = []
node_export_rows = []

for fname, item in parsed.items():
    df = item["df"].copy()
    plane = item["plane_detected"]
    mode = item["mode"]

    # Select ROI
    if plane == "XZ":
        roi = df[
            (df["x"] >= ROI_XZ["x_min"]) & (df["x"] <= ROI_XZ["x_max"]) &
            (df["z"] >= ROI_XZ["z_min"]) & (df["z"] <= ROI_XZ["z_max"])
        ].copy()

    elif plane == "YZ":
        roi = df[
            (df["y"] >= ROI_YZ["y_min"]) & (df["y"] <= ROI_YZ["y_max"]) &
            (df["z"] >= ROI_YZ["z_min"]) & (df["z"] <= ROI_YZ["z_max"])
        ].copy()

    else:
        roi = pd.DataFrame(columns=df.columns)

    # Metrics
    if len(roi) == 0:
        E_peak = np.nan
        E_mean = np.nan
        E_std = np.nan
        N_points = 0
    else:
        E_peak = roi["Field"].max()
        E_mean = roi["Field"].mean()
        E_std  = roi["Field"].std(ddof=1) if len(roi) > 1 else 0.0
        N_points = len(roi)

    summary_rows.append({
        "Mode": mode,
        "Plane": plane,
        "Filename": fname,
        "ROI_Points": N_points,
        "E_peak (V/m)": E_peak,
        "E_mean (V/m)": E_mean,
        "E_standardDeviation (V/m)": E_std,
        "File_Min (V/m)": item["minval_file"],
        "File_Max (V/m)": item["maxval_file"]
    })

    # Optional: keep ROI node data for checking
    if len(roi) > 0:
        roi_export = roi.copy()
        roi_export.insert(0, "Mode", mode)
        roi_export.insert(1, "Plane", plane)
        roi_export.insert(2, "Filename", fname)
        node_export_rows.append(roi_export)

summary_df = pd.DataFrame(summary_rows)
summary_df = summary_df.sort_values(["Plane", "Mode"]).reset_index(drop=True)

if len(node_export_rows) > 0:
    roi_nodes_df = pd.concat(node_export_rows, ignore_index=True)
else:
    roi_nodes_df = pd.DataFrame(columns=["Mode", "Plane", "Filename", "x", "y", "z", "Field"])

print(summary_df)

