# -*- coding: utf-8 -*-
"""J_surface_aedtplt_reconfiguration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f27naK2_dSEKF8sFA5M5iu5p1saf052w

Data parse
"""

# ============================================
# Colab script:
# PIN diode-region current concentration + flow direction
# from Mag_Jsurf and Vec_Jsurf .aedtplt files in one ZIP
# ============================================

import re
import os
import glob
import zipfile
import shutil
import numpy as np
import pandas as pd
from google.colab import files

# =========================================================
# 1) Upload one ZIP file
# =========================================================
uploaded = files.upload()
zip_name = list(uploaded.keys())[0]

extract_folder = "/content/current_zip_extract"

if os.path.exists(extract_folder):
    shutil.rmtree(extract_folder)
os.makedirs(extract_folder, exist_ok=True)

with zipfile.ZipFile(zip_name, "r") as zf:
    zf.extractall(extract_folder)

print(f"ZIP extracted to: {extract_folder}")

# =========================================================
# 2) Find all .aedtplt files
# =========================================================
file_list = sorted(glob.glob(os.path.join(extract_folder, "**", "*.aedtplt"), recursive=True))

if len(file_list) == 0:
    raise FileNotFoundError("No .aedtplt files found inside the uploaded ZIP.")

print(f"Found {len(file_list)} .aedtplt files")

# =========================================================
# 3) Parsing helpers
# =========================================================
def extract_block(text, key):
    start = text.find(f"{key}(")
    if start == -1:
        raise ValueError(f"{key}( not found in file")

    i = start + len(key) + 1
    depth = 1
    out = []

    while i < len(text) and depth > 0:
        ch = text[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                break
        out.append(ch)
        i += 1

    return "".join(out)

def parse_float_list(s):
    return [float(x) for x in re.findall(r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', s)]

def parse_int_list(s):
    return [int(x) for x in re.findall(r'[-+]?\d+', s)]

def parse_nodes(nodes_text):
    vals = parse_float_list(nodes_text)
    return np.array(vals).reshape(-1, 3)

def parse_elements(elements_text):
    arr = parse_int_list(elements_text)
    total_nodes = arr[0]
    total_elements = arr[1]

    pos = 2
    elements = []

    for _ in range(total_elements):
        header = arr[pos:pos+5]
        n_nodes = header[4]
        conn = arr[pos+5:pos+5+n_nodes]
        pos += 5 + n_nodes
        elements.append({
            "header": header,
            "n_nodes": n_nodes,
            "conn": conn
        })

    return total_nodes, total_elements, elements

def parse_elem_solution(elemsol_text):
    vals = parse_float_list(elemsol_text)
    minval = vals[0]
    maxval = vals[1]
    n_per_element = int(vals[2])
    data = vals[3:]
    return minval, maxval, n_per_element, data

def build_nodal_scalar_field(nodes, elements, n_per_element, elem_data):
    nodal_sum = np.zeros(len(nodes), dtype=float)
    nodal_count = np.zeros(len(nodes), dtype=int)

    pos = 0
    for el in elements:
        n_nodes = el["n_nodes"]
        vals = elem_data[pos:pos+n_per_element]
        pos += n_per_element

        if n_per_element != n_nodes:
            raise ValueError(f"Scalar file expected n_per_element={n_nodes}, got {n_per_element}")

        for node_idx_1based, fval in zip(el["conn"], vals):
            idx = node_idx_1based - 1
            nodal_sum[idx] += fval
            nodal_count[idx] += 1

    return nodal_sum / np.where(nodal_count == 0, 1, nodal_count)

def build_nodal_vector_field(nodes, elements, n_per_element, elem_data):
    vec_sum = np.zeros((len(nodes), 3), dtype=float)
    vec_count = np.zeros(len(nodes), dtype=int)

    pos = 0
    for el in elements:
        n_nodes = el["n_nodes"]
        vals = elem_data[pos:pos+n_per_element]
        pos += n_per_element

        if n_per_element != 3 * n_nodes:
            raise ValueError(f"Vector file expected n_per_element={3*n_nodes}, got {n_per_element}")

        for local_idx, node_idx_1based in enumerate(el["conn"]):
            idx = node_idx_1based - 1
            jx = vals[3 * local_idx + 0]
            jy = vals[3 * local_idx + 1]
            jz = vals[3 * local_idx + 2]
            vec_sum[idx, 0] += jx
            vec_sum[idx, 1] += jy
            vec_sum[idx, 2] += jz
            vec_count[idx] += 1

    return vec_sum / np.where(vec_count[:, None] == 0, 1, vec_count[:, None])

def parse_mode_and_kind_from_filename(filepath):
    base = os.path.basename(filepath)
    low = base.lower()

    mode_match = re.search(r'\[?([01]{3})\]?', base)
    mode = mode_match.group(1) if mode_match else "UNK"

    if ("mag_jsurf" in low) or ("mag" in low and "jsurf" in low):
        kind = "MAG"
    elif ("vec_jsurf" in low) or ("vector_jsurf" in low) or ("vec" in low and "jsurf" in low):
        kind = "VEC"
    else:
        kind = "UNK"

    return mode, kind

def parse_aedtplt_file(filepath):
    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    nodes = parse_nodes(extract_block(text, "Nodes"))
    _, _, elements = parse_elements(extract_block(text, "Elements"))
    minval, maxval, n_per_element, elem_data = parse_elem_solution(extract_block(text, "ElemSolution"))

    mode, kind_name = parse_mode_and_kind_from_filename(filepath)
    n_nodes_first = elements[0]["n_nodes"]

    if n_per_element == n_nodes_first:
        jmag = build_nodal_scalar_field(nodes, elements, n_per_element, elem_data)
        df = pd.DataFrame({
            "x": nodes[:, 0],
            "y": nodes[:, 1],
            "z": nodes[:, 2],
            "Jmag": jmag
        })
        data_type = "MAG"

    elif n_per_element == 3 * n_nodes_first:
        jvec = build_nodal_vector_field(nodes, elements, n_per_element, elem_data)
        jmag = np.linalg.norm(jvec, axis=1)
        df = pd.DataFrame({
            "x": nodes[:, 0],
            "y": nodes[:, 1],
            "z": nodes[:, 2],
            "Jx": jvec[:, 0],
            "Jy": jvec[:, 1],
            "Jz": jvec[:, 2],
            "Jmag": jmag
        })
        data_type = "VEC"

    else:
        raise ValueError(f"Unsupported file format: n_per_element={n_per_element}")

    return {
        "filepath": filepath,
        "filename": os.path.basename(filepath),
        "mode": mode,
        "kind": data_type if kind_name == "UNK" else kind_name,
        "df": df
    }

# =========================================================
# 4) Parse all files
# =========================================================
mag_files = {}
vec_files = {}
failed_files = []

for filepath in file_list:
    try:
        item = parse_aedtplt_file(filepath)

        if item["kind"] == "MAG":
            mag_files[item["mode"]] = item
        elif item["kind"] == "VEC":
            vec_files[item["mode"]] = item
        else:
            failed_files.append({"Filename": os.path.basename(filepath), "Error": "Unknown file type"})

        print(f"Parsed: {item['filename']} | mode={item['mode']} | kind={item['kind']}")

    except Exception as e:
        failed_files.append({"Filename": os.path.basename(filepath), "Error": str(e)})
        print(f"Failed: {os.path.basename(filepath)} -> {e}")

# =========================================================
# 5) Define PIN diode regions Ω_Pi and reference vector v0
#    !!! EDIT THESE VALUES !!!
# =========================================================
PIN_REGIONS = {
    "P1": {
        "x_min": -6.0, "x_max":  2.0,
        "y_min": -19.0, "y_max":  -13.0,
        "z_min": 0, "z_max":  3,
        "v0": [-1.0, 0.0, 0.0]
    },
    "P2": {
        "x_min":  -6.0, "x_max":  2.0,
        "y_min": 10.0, "y_max":  16.0,
        "z_min": 0, "z_max":  3,
        "v0": [-1, 0.0, 0.0]
    },
    "P3": {
        "x_min": -6.0, "x_max": 2,
        "y_min": -12.0, "y_max":  -6.0,
        "z_min": 0, "z_max":  3,
        "v0": [-1.0, 0.0, 0.0]
    }
}

def select_region(df, reg):
    return df[
        (df["x"] >= reg["x_min"]) & (df["x"] <= reg["x_max"]) &
        (df["y"] >= reg["y_min"]) & (df["y"] <= reg["y_max"]) &
        (df["z"] >= reg["z_min"]) & (df["z"] <= reg["z_max"])
    ].copy()

# =========================================================
# 6) Compute J_Pi and V_Pi
# =========================================================
rows = []
all_modes = sorted(set(mag_files.keys()) | set(vec_files.keys()))

for mode in all_modes:
    mag_df = mag_files.get(mode, {}).get("df", pd.DataFrame())
    vec_df = vec_files.get(mode, {}).get("df", pd.DataFrame())

    for pname, reg in PIN_REGIONS.items():
        # --------------------------
        # Current concentration: J_Pi
        # --------------------------
        mag_roi = select_region(mag_df, reg) if not mag_df.empty else pd.DataFrame()

        if len(mag_roi) == 0:
            JPi = np.nan
            N_mag = 0
        else:
            JPi = mag_roi["Jmag"].mean()
            N_mag = len(mag_roi)

        # --------------------------
        # Flow direction: V_Pi
        # --------------------------
        vec_roi = select_region(vec_df, reg) if not vec_df.empty else pd.DataFrame()

        if len(vec_roi) == 0:
            VPi = np.nan
            N_vec = 0
        else:
            v0 = np.array(reg["v0"], dtype=float)
            v0 = v0 / np.linalg.norm(v0)

            J = vec_roi[["Jx", "Jy", "Jz"]].to_numpy()
            Jmag = np.linalg.norm(J, axis=1)

            proj = np.sum(J * v0[None, :], axis=1) / (Jmag + 1e-12)
            VPi = np.mean(proj)
            N_vec = len(vec_roi)

        rows.append({
            "Mode": f"[{mode}]" if mode != "UNK" else mode,
            "PIN_Region": pname,
            "N_mag": N_mag,
            "J_Pi (A/m)": JPi,
            "N_vec": N_vec,
            "V_Pi": VPi
        })

result_df = pd.DataFrame(rows)

# =========================================================
# 7) Sort by binary mode order
# =========================================================
def mode_sort_key(x):
    x = str(x).replace("[", "").replace("]", "")
    return int(x, 2) if re.fullmatch(r"[01]{3}", x) else 999

result_df["Mode_sort"] = result_df["Mode"].apply(mode_sort_key)
result_df = result_df.sort_values(["Mode_sort", "PIN_Region"]).drop(columns=["Mode_sort"]).reset_index(drop=True)

print("\nLong-format results:")
print(result_df)

# =========================================================
# 8) Wide summary by mode
# =========================================================
wide_df = result_df.pivot_table(
    index="Mode",
    columns="PIN_Region",
    values=["J_Pi (A/m)", "V_Pi"],
    aggfunc="first"
)

if not wide_df.empty:
    wide_df.columns = [f"{metric}_{region}" for metric, region in wide_df.columns]
    wide_df = wide_df.reset_index()
    wide_df["Mode_sort"] = wide_df["Mode"].apply(mode_sort_key)
    wide_df = wide_df.sort_values("Mode_sort").drop(columns=["Mode_sort"]).reset_index(drop=True)

print("\nWide summary by mode:")
print(wide_df)

failed_df = pd.DataFrame(failed_files)

# =========================================================
# 9) Save to Excel
# =========================================================
output_file = "PIN_current_concentration_and_direction.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    result_df.to_excel(writer, sheet_name="Long_Format", index=False)
    wide_df.to_excel(writer, sheet_name="Wide_By_Mode", index=False)
    failed_df.to_excel(writer, sheet_name="Failed_Files", index=False)

files.download(output_file)
print(f"\nSaved: {output_file}")

"""Data process"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================
# 1) Input data
# ============================================
data = {
    "Mode": ["[000]", "[001]", "[010]", "[011]", "[100]", "[101]", "[110]", "[111]"],
    "J_P1 (A/m)": [5.019461, 9.49661, 6.266419, 10.506965, 7.744568, 8.1846, 8.454099, 9.788999],
    "J_P2 (A/m)": [9.57377, 11.257126, 11.420799, 13.336229, 10.757992, 7.481718, 11.215475, 11.226977],
    "J_P3 (A/m)": [1.306312, 4.242322, 1.61856, 4.238266, 2.509411, 4.243618, 2.484529, 4.391063],
    "V_P1": [-0.035477, -0.042062, -0.03704, -0.068195, 0.347042, 0.266772, 0.331766, 0.176339],
    "V_P2": [-0.074122, -0.07511, 0.084175, 0.04103, -0.11196, -0.08293, 0.110575, 0.099676],
    "V_P3": [0.513003, 0.320744, 0.486896, 0.315558, 0.315797, 0.440597, 0.314428, 0.381091]
}

df = pd.DataFrame(data)

# sort mode in binary order
def mode_sort_key(x):
    return int(str(x).replace("[", "").replace("]", ""), 2)

df["Mode_sort"] = df["Mode"].apply(mode_sort_key)
df = df.sort_values("Mode_sort").drop(columns=["Mode_sort"]).reset_index(drop=True)

# ============================================x
# 2) Build heatmap matrices
# ============================================
J_mat = df.set_index("Mode")[["J_P1 (A/m)", "J_P2 (A/m)", "J_P3 (A/m)"]].copy()
J_mat.columns = ["P1", "P2", "P3"]

V_mat = df.set_index("Mode")[["V_P1", "V_P2", "V_P3"]].copy()
V_mat.columns = ["P1", "P2", "P3"]

# ============================================
# 3) Plot two heatmaps
# ============================================
sns.set_theme(style="white", font_scale=1.0)

fig, axes = plt.subplots(1, 2, figsize=(11, 5), constrained_layout=True)

# J heatmap
sns.heatmap(
    J_mat,
    ax=axes[0],
    annot=True,
    fmt=".2f",
    cmap="YlOrRd",
    linewidths=0.5,
    linecolor="white",
    cbar=True
)
axes[0].set_title(r"Current concentration $J_{P_i}^{(m)}$")
axes[0].set_xlabel("PIN region")
axes[0].set_ylabel("Mode")

# V heatmap
sns.heatmap(
    V_mat,
    ax=axes[1],
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
    center=0,
    linewidths=0.5,
    linecolor="white",
    cbar=True
)
axes[1].set_title(r"Flow-direction index $V_{P_i}^{(m)}$")
axes[1].set_xlabel("PIN region")
axes[1].set_ylabel("Mode")

plt.show()

"""changable plotting"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================
# 0) USER CONTROLS
# ============================================
FIG_WIDTH = 12          # whole figure width
FIG_HEIGHT = 5          # whole figure height
FONT_SCALE = 1.0        # seaborn font scale
SHOW_NUMBERS = True     # True / False
ANNOT_FMT = ".2f"       # number format in heatmap cells

J_CMAP = "YlOrRd"       # heatmap for current concentration
V_CMAP = "coolwarm"     # heatmap for flow-direction index
V_VMIN = -1             # fixed range for V
V_VMAX = 1
V_CENTER = 0

# ============================================
# 1) Input data
# ============================================
data = {
    "Mode": ["[000]", "[001]", "[010]", "[011]", "[100]", "[101]", "[110]", "[111]"],
    "J_P1 (A/m)": [5.019461, 9.49661, 6.266419, 10.506965, 7.744568, 8.1846, 8.454099, 9.788999],
    "J_P2 (A/m)": [9.57377, 11.257126, 11.420799, 13.336229, 10.757992, 7.481718, 11.215475, 11.226977],
    "J_P3 (A/m)": [1.306312, 4.242322, 1.61856, 4.238266, 2.509411, 4.243618, 2.484529, 4.391063],
    "V_P1": [-0.035477, -0.042062, -0.03704, -0.068195, 0.347042, 0.266772, 0.331766, 0.176339],
    "V_P2": [-0.074122, -0.07511, 0.084175, 0.04103, -0.11196, -0.08293, 0.110575, 0.099676],
    "V_P3": [0.513003, 0.320744, 0.486896, 0.315558, 0.315797, 0.440597, 0.314428, 0.381091]
}

df = pd.DataFrame(data)

# ============================================
# 2) Sort modes in binary order
# ============================================
def mode_sort_key(x):
    return int(str(x).replace("[", "").replace("]", ""), 2)

df["Mode_sort"] = df["Mode"].apply(mode_sort_key)
df = df.sort_values("Mode_sort").drop(columns=["Mode_sort"]).reset_index(drop=True)

# ============================================
# 3) Heatmap matrices
# ============================================
J_mat = df.set_index("Mode")[["J_P1 (A/m)", "J_P2 (A/m)", "J_P3 (A/m)"]].copy()
J_mat.columns = ["P1", "P2", "P3"]

V_mat = df.set_index("Mode")[["V_P1", "V_P2", "V_P3"]].copy()
V_mat.columns = ["P1", "P2", "P3"]

# ============================================
# 4) Plot two heatmaps
# ============================================
sns.set_theme(style="white", font_scale=FONT_SCALE)

fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH, FIG_HEIGHT), constrained_layout=True)

sns.heatmap(
    J_mat,
    ax=axes[0],
    #annot=SHOW_NUMBERS,
    fmt=ANNOT_FMT,
    cmap=J_CMAP,
    linewidths=0.5,
    linecolor="white",
    cbar=True
)
axes[0].set_title(r"Current concentration $J_{P_i}^{(m)}$")
axes[0].set_xlabel("PIN region")
axes[0].set_ylabel("Mode")

sns.heatmap(
    V_mat,
    ax=axes[1],
    #annot=SHOW_NUMBERS,
    fmt=ANNOT_FMT,
    cmap=V_CMAP,
    vmin=V_VMIN,
    vmax=V_VMAX,
    center=V_CENTER,
    linewidths=0.5,
    linecolor="white",
    cbar=True
)
axes[1].set_title(r"Flow-direction index $V_{P_i}^{(m)}$")
axes[1].set_xlabel("PIN region")
axes[1].set_ylabel("Mode")
SAVE_SVG = True
SVG_FILENAME = "j-surf.svg"
plt.savefig(SVG_FILENAME, format="svg", bbox_inches="tight")
plt.show()

# ============================================
# 5) Direction-control metric
#    [b1 b2 b3] means P1=b1, P2=b2, P3=b3
# ============================================
def bit_of_mode(mode_str, bit_index):
    bits = str(mode_str).replace("[", "").replace("]", "")
    return int(bits[bit_index])

# Add ON/OFF columns
df["P1_state"] = df["Mode"].apply(lambda x: bit_of_mode(x, 0))
df["P2_state"] = df["Mode"].apply(lambda x: bit_of_mode(x, 1))
df["P3_state"] = df["Mode"].apply(lambda x: bit_of_mode(x, 2))

direction_control_rows = []

for pin in ["P1", "P2", "P3"]:
    Vcol = f"V_{pin}"
    state_col = f"{pin}_state"

    v_on = df[df[state_col] == 1][Vcol].mean()
    v_off = df[df[state_col] == 0][Vcol].mean()
    D = abs(v_on - v_off)

    direction_control_rows.append({
        "PIN": pin,
        "Mean_V_when_ON": v_on,
        "Mean_V_when_OFF": v_off,
        "Direction_Control_Index": D
    })

direction_df = pd.DataFrame(direction_control_rows).sort_values(
    "Direction_Control_Index", ascending=False
).reset_index(drop=True)

print("Direction-control summary:")
print(direction_df)

dominant_pin = direction_df.loc[0, "PIN"]
print(f"\nPIN diode with the strongest directional control: {dominant_pin}")